/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Attendances {
  break_begin: string | null;
  break_end: string | null;
  clockIn: string;
  clockOut: string | null;
  created_at: Date | null;
  date: Date;
  empId: number;
  id: Generated<number>;
  status: string | null;
  updated_at: Date | null;
}

export interface Attributes {
  attr_name: string;
  category_id: number;
  created_at: Date | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  is_opensource: Generated<number>;
  is_required: Generated<number>;
  order_no: number | null;
  show_description: number;
  show_image: number;
  show_in_classic_card: number;
  show_in_smart_card: number;
  subcategory_id: number;
  updated_at: Date | null;
}

export interface AttributeValues {
  attr_id: number;
  category_id: number;
  created_at: Date | null;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  is_deleted: Generated<number>;
  subcategory_id: number;
  updated_at: Date | null;
  value_name: string;
}

export interface Banners {
  created_at: Date | null;
  id: Generated<number>;
  img_type: string;
  mobile_slider: string | null;
  name: string | null;
  path: string;
  status: number;
  updated_at: Date | null;
  url: string | null;
}

export interface Blogs {
  added_by: number;
  banner: string | null;
  canonical: string | null;
  content: string;
  created_at: Date | null;
  id: Generated<number>;
  meta_description: string | null;
  meta_keywords: string | null;
  meta_title: string | null;
  page_name: string;
  slug: string;
  thumbnail: string | null;
  updated_at: Date | null;
}

export interface Branches {
  acdnbd1: string | null;
  acdnbd2: string | null;
  acdnbd3: string | null;
  acdnitm1: string | null;
  acdnitm2: string | null;
  acdnitm3: string | null;
  alt: string | null;
  canonical: string | null;
  city: string | null;
  content: string | null;
  created_at: Generated<Date>;
  description: string | null;
  h1: string | null;
  id: Generated<number>;
  img: string | null;
  intro: string | null;
  keywords: string | null;
  pageURL: string | null;
  schm: string | null;
  title: string | null;
  updated_at: Generated<Date>;
}

export interface Categories {
  added_by: number;
  banner: string | null;
  created_at: Date | null;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  name: string;
  short_description: string | null;
  unit: string;
  updated_at: Date | null;
}

export interface Employements {
  created_at: Date | null;
  id: Generated<number>;
  is_working: string;
  joining_date: string;
  leave_date: string | null;
  parent_id: number;
  remark: string | null;
  salary: string;
  updated_at: Date | null;
  user_id: number;
}

export interface FailedJobs {
  connection: string;
  exception: string;
  failed_at: Generated<Date>;
  id: number;
  payload: string;
  queue: string;
}

export interface Formlayouts {
  category_id: number;
  created_at: Date | null;
  id: Generated<number>;
  label_name: string;
  label_order: number | null;
  placeholder: string;
  show_in_card: string;
  updated_at: Date | null;
}

export interface Holidays {
  created_at: Date | null;
  date: Date;
  id: Generated<number>;
  occasion: string;
  status: number;
  updated_at: Date | null;
  userid: number;
}

export interface Migrations {
  batch: number;
  id: Generated<number>;
  migration: string;
}

export interface OrderDetails {
  category_id: number;
  classic_card: number;
  created_at: Date | null;
  id: Generated<number>;
  order_id: number;
  qty: number;
  smart_card: number;
  updated_at: Date | null;
}

export interface Orders {
  address: string | null;
  alt_mobile: string | null;
  assigned_date: string | null;
  assigned_to: number | null;
  created_at: Date | null;
  customer_name: string;
  deliver_by: number | null;
  delivery_date: string | null;
  discount: number | null;
  dues_amount: string | null;
  dues_date: string | null;
  email: string | null;
  gst: string | null;
  id: Generated<number>;
  lab_id: number;
  mobile: string;
  order_date: string;
  order_no: string;
  paid_amount: string | null;
  pay_mode: string | null;
  payable_amt: number | null;
  received_by: number;
  show_image_in_card: number | null;
  show_image_in_card_file: string | null;
  show_name_in_card: Generated<number>;
  show_name_input: string | null;
  status: string;
  total_amount: string | null;
  transaction_no: string | null;
  updated_at: Date | null;
}

export interface PasswordResets {
  created_at: Date | null;
  email: string;
  token: string;
}

export interface Prices {
  category_id: string;
  classic_price: number;
  created_at: Date | null;
  id: Generated<number>;
  lab_id: string | null;
  max_wt: number;
  min_wt: number;
  rate: string;
  smart_price: number;
  updated_at: Date | null;
}

export interface Reports {
  carat_weight: string;
  classic_card_price: string;
  comments: string | null;
  created_at: Date | null;
  description: string;
  gross_weight: string;
  gross_wt_unit: number;
  id: Generated<number>;
  is_approx: Generated<number>;
  item_image: string;
  lab_id: number;
  order_detail_id: string;
  order_no: string;
  report_no: string;
  size: string | null;
  smart_card_price: string;
  stone_wt_unit: number;
  subcategory_id: string;
  updated_at: Date | null;
  user_id: number;
}

export interface Reportsearches {
  created_at: Date | null;
  fullname: string;
  id: Generated<number>;
  mobile: string;
  report_no: string;
  updated_at: Date | null;
}

export interface Reporttypes {
  added_by: number;
  banner: string | null;
  created_at: Date | null;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  meta_description: string | null;
  meta_keywords: string | null;
  meta_title: string | null;
  name: string;
  short_description: string | null;
  slug: string;
  updated_at: Date | null;
}

export interface RolePermissions {
  action_type: string;
  create: number;
  created_at: Date | null;
  delete: number;
  id: Generated<number>;
  role_id: number;
  update: number;
  updated_at: Date | null;
  view: number;
}

export interface Roles {
  created_at: Date | null;
  id: Generated<number>;
  role_name: string;
  updated_at: Date | null;
}

export interface Subcategories {
  added_by: number;
  banner: string | null;
  category_id: number;
  created_at: Date | null;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  name: string;
  updated_at: Date | null;
}

export interface Transactions {
  amount: string;
  attachment: string | null;
  comission_on: number | null;
  created_at: Date | null;
  id: Generated<number>;
  order_id: number | null;
  pay_mode: string;
  received_by: number;
  remark: string | null;
  seen_by_receiver: number;
  seen_by_sender: number;
  send_by: number;
  status: number;
  transaction_no: string | null;
  transaction_type: string | null;
  updated_at: Date | null;
}

export interface Units {
  created_at: Date | null;
  id: Generated<number>;
  name: string;
  rate: string;
  symbol: string;
  updated_at: Date | null;
}

export interface Users {
  account_no: string | null;
  address: string | null;
  adhar_no: string | null;
  adhar_photo: string | null;
  alt_mobile: string | null;
  bank_name: string | null;
  city: string | null;
  commision: number | null;
  company_logo: string | null;
  country: string | null;
  created_at: Date | null;
  documentation: string | null;
  email: string | null;
  empid: string | null;
  fax: string | null;
  fullname: string;
  gst_no: string | null;
  id: Generated<number>;
  ifsc_code: string | null;
  is_active: number;
  mobile: string;
  owner_name: string | null;
  pan_no: string | null;
  pan_photo: string | null;
  password: string;
  pincode: string | null;
  profile_photo: string | null;
  remember_token: string | null;
  role_id: number;
  signature: string | null;
  state: string | null;
  status: number;
  updated_at: Date | null;
}

export interface Websites {
  banner: string | null;
  content: string;
  created_at: Date | null;
  id: Generated<number>;
  meta_description: string | null;
  meta_keywords: string | null;
  meta_title: string | null;
  page_name: string;
  page_type: string;
  updated_at: Date | null;
}

export interface DB {
  attendances: Attendances;
  attribute_values: AttributeValues;
  attributes: Attributes;
  banners: Banners;
  blogs: Blogs;
  branches: Branches;
  categories: Categories;
  employements: Employements;
  failed_jobs: FailedJobs;
  formlayouts: Formlayouts;
  holidays: Holidays;
  migrations: Migrations;
  order_details: OrderDetails;
  orders: Orders;
  password_resets: PasswordResets;
  prices: Prices;
  reports: Reports;
  reportsearches: Reportsearches;
  reporttypes: Reporttypes;
  role_permissions: RolePermissions;
  roles: Roles;
  subcategories: Subcategories;
  transactions: Transactions;
  units: Units;
  users: Users;
  websites: Websites;
}
